/**
 * These types will be auto-generated by `pnpm db:types` but serve as initial reference.
 */

export type UserRole = 'admin' | 'coach' | 'athlete' | 'scout' | 'guardian' | 'medical';
export type PositionType = 'GK' | 'CB' | 'LB' | 'RB' | 'CDM' | 'CM' | 'CAM' | 'LW' | 'RW' | 'ST';
export type DominantFoot = 'left' | 'right' | 'both';
export type CategoryType = 'U11' | 'U13' | 'U15' | 'U17' | 'U20' | 'PRO';
export type RelationshipType = 'parent' | 'guardian' | 'agent' | 'other';
export type MatchStatus = 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
export type EventType = 'goal' | 'assist' | 'yellow_card' | 'red_card' | 'substitution_in' | 'substitution_out';
export type SessionType = 'training' | 'recovery' | 'gym' | 'match';
export type AcwrZone = 'undertrained' | 'optimal' | 'warning' | 'danger';
export type ReportType = 'match_analysis' | 'scouting' | 'development';
export type AiSourceType = 'gemini' | 'openai';
export type AssetType = 'video' | 'image' | 'document';
export type TagType = 'tactical' | 'technical' | 'physical' | 'mental';
export type RecommendationType = 'training' | 'rest' | 'nutrition' | 'medical';
export type ScoutStatus = 'evaluating' | 'following' | 'offered' | 'rejected';
export type CycleType = 'weekly' | 'monthly' | 'season';
export type IdpStatus = 'active' | 'completed' | 'paused';
export type IdpCategory = 'technical' | 'tactical' | 'physical' | 'mental';
export type GoalStatus = 'not_started' | 'in_progress' | 'achieved' | 'missed';
export type PhvStatus = 'pre_phv' | 'phv' | 'post_phv';
export type NotificationType = 'system' | 'message' | 'alert' | 'reminder';
export type ConsentType = 'privacy_policy' | 'terms_of_service' | 'data_processing';
export type DataRequestType = 'export' | 'delete' | 'modify';
export type DataRequestStatus = 'pending' | 'processing' | 'completed' | 'rejected';

export interface User {
  id: string;
  email: string;
  role: UserRole;
  created_at: string;
  updated_at: string;
}

export interface Athlete {
  id: string;
  user_id: string;
  first_name: string;
  last_name: string;
  date_of_birth: string;
  position: PositionType;
  dominant_foot: DominantFoot;
  category: CategoryType;
  height_cm: number;
  weight_kg: number;
}

export interface CoachProfile {
  id: string;
  user_id: string;
  specialization: string;
}

export interface ScoutProfile {
  id: string;
  user_id: string;
  region: string;
}

export interface GuardianAthlete {
  id: string;
  guardian_id: string;
  athlete_id: string;
  relationship: RelationshipType;
}

export interface Match {
  id: string;
  date: string;
  opponent: string;
  home_team: boolean;
  status: MatchStatus;
}

export interface MatchEvent {
  id: string;
  match_id: string;
  athlete_id: string;
  event_type: EventType;
  minute: number;
}

export interface TrainingSession {
  id: string;
  date: string;
  type: SessionType;
  duration_minutes: number;
}

export interface TrainingFeedback {
  id: string;
  session_id: string;
  athlete_id: string;
  rpe: number;
}

export interface WellnessLog {
  id: string;
  athlete_id: string;
  date: string;
  sleep: number;
  fatigue: number;
  soreness: number;
  stress: number;
  mood: number;
}

export interface WorkloadMetrics {
  id: string;
  athlete_id: string;
  date: string;
  acute_load: number;
  chronic_load: number;
  acwr: number;
  acwr_zone: AcwrZone;
}

export interface AIReport {
  id: string;
  athlete_id: string;
  report_type: ReportType;
  source: AiSourceType;
  content: string;
  created_at: string;
}

export interface AIEmbedding {
  id: string;
  reference_id: string;
  embedding: number[];
}

export interface MediaAsset {
  id: string;
  url: string;
  type: AssetType;
  athlete_id: string;
}

export interface VideoTag {
  id: string;
  asset_id: string;
  tag_type: TagType;
  timestamp: number;
}

export interface ScoutingReport {
  id: string;
  scout_id: string;
  athlete_id: string;
  notes: string;
}

export interface ScoutInterest {
  id: string;
  scout_id: string;
  athlete_id: string;
  status: ScoutStatus;
}

export interface IndividualDevelopmentPlan {
  id: string;
  athlete_id: string;
  cycle: CycleType;
  status: IdpStatus;
}

export interface IdpGoal {
  id: string;
  idp_id: string;
  category: IdpCategory;
  description: string;
  status: GoalStatus;
}

export interface MaturationRecord {
  id: string;
  athlete_id: string;
  date: string;
  standing_height: number;
  sitting_height: number;
  weight: number;
  phv_status: PhvStatus;
}

export interface Notification {
  id: string;
  user_id: string;
  type: NotificationType;
  message: string;
  read: boolean;
  created_at: string;
}

export interface AuditLog {
  id: string;
  user_id: string;
  action: string;
  resource: string;
  timestamp: string;
}

export interface FeatureFlag {
  id: string;
  name: string;
  enabled: boolean;
}

export interface AppSetting {
  id: string;
  key: string;
  value: string;
}

export interface ConsentRecord {
  id: string;
  user_id: string;
  consent_type: ConsentType;
  version: string;
  accepted_at: string;
}

export interface DataSubjectRequest {
  id: string;
  user_id: string;
  request_type: DataRequestType;
  status: DataRequestStatus;
  created_at: string;
}

export interface DataAccessLog {
  id: string;
  user_id: string;
  accessed_resource: string;
  timestamp: string;
}
