-- Sprint 13: Expand matches table with advanced stats

ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS minutes_played INTEGER,
  ADD COLUMN IF NOT EXISTS yellow_cards INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS red_cards INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS shots INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS shots_on_target INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dribbles_successful INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS passes_completed INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pass_accuracy_percentage INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS crosses INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tackles INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS interceptions INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS aerial_duels_won INTEGER DEFAULT 0;
