CREATE TYPE user_role AS ENUM ('athlete', 'coach', 'scout', 'admin');
CREATE TYPE position_type AS ENUM ('goalkeeper', 'defender', 'midfielder', 'forward');
CREATE TYPE dominant_foot AS ENUM ('left', 'right', 'both');
CREATE TYPE category_type AS ENUM ('u15', 'u17', 'u20', 'pro');
CREATE TYPE relationship_type AS ENUM ('parent', 'agent', 'guardian');
CREATE TYPE match_status AS ENUM ('pending_analysis', 'analyzed', 'archived');
CREATE TYPE event_type AS ENUM ('goal', 'assist', 'yellow_card', 'red_card', 'substitution', 'highlight');
CREATE TYPE session_type AS ENUM ('training', 'recovery', 'gym', 'match');
CREATE TYPE acwr_zone AS ENUM ('danger_low', 'sweet_spot', 'danger_high');
CREATE TYPE report_type AS ENUM ('match_analysis', 'monthly_progress', 'scouting_summary');
CREATE TYPE ai_source_type AS ENUM ('video', 'match_data', 'training_data', 'profile');
CREATE TYPE asset_type AS ENUM ('video', 'image', 'document');
CREATE TYPE tag_type AS ENUM ('offensive', 'defensive', 'technical', 'tactical');
CREATE TYPE recommendation_type AS ENUM ('sign', 'monitor', 'reject');
CREATE TYPE scout_status AS ENUM ('pending', 'contacted', 'rejected', 'signed');
CREATE TYPE cycle_type AS ENUM ('weekly', 'monthly', 'quarterly', 'yearly');
CREATE TYPE idp_status AS ENUM ('active', 'completed', 'archived');
CREATE TYPE idp_category AS ENUM ('technical', 'tactical', 'physical', 'mental');
CREATE TYPE goal_status AS ENUM ('not_started', 'in_progress', 'achieved', 'abandoned');
CREATE TYPE phv_status AS ENUM ('pre', 'circa', 'post');
CREATE TYPE notification_type AS ENUM ('system', 'message', 'alert', 'reminder');
CREATE TYPE consent_type AS ENUM ('terms_of_service', 'privacy_policy', 'data_processing', 'marketing');
CREATE TYPE data_request_type AS ENUM ('export', 'deletion', 'correction');
CREATE TYPE data_request_status AS ENUM ('pending', 'processing', 'completed', 'rejected');
